services:
  db:
    image: postgres:17
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: meeting
      POSTGRES_PASSWORD: password

  adminer:
    image: adminer
    ports:
      - 8080:8080
